version: "3.0"
services: 
  sb-server:
    container_name: sb-server
    restart: always
    build: .
    ports:
      - 8080:8080 
    environment:
      DB_HOST: sb-mysqldb
      DB_NAME: icaredb
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
    networks:
      - sb-bridge

  sb-mysqldb:
    container_name: sb-mysqldb
    image: mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_DATABASE: icaredb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - sb-bridge

networks:
  sb-bridge:
    name: sb-bridge
    external: true
    driver: bridge

