version: "3.0"
services: 
  sb-client:
    container_name: sb-client
    restart: always
    build: .
    ports:
      - 3000:3000 
    environment:
      REACT_APP_SERVER_NAME: sb-server
      REACT_APP_SERVER_PORT: 8080
      REACT_APP_CLIENT_K8S: icare-client
    networks:
      - sb-bridge

networks:
  sb-bridge:
    name: sb-bridge
    external: true
    driver: bridge

