version: "3.0"
services: 
  sb-client:
    container_name: sb-client
    restart: always
    build: .
    ports:
      - 3000:3000 
#   environment:
#     SB_SERVER_HOST: sb-server
#     SB_SERVER_PORT: 8080
    networks:
      - sb-bridge

networks:
  sb-bridge:
    name: sb-bridge
    external: true
    driver: bridge

